# Data Cleaning and Analysis

In this notebook we are going to make some data cleaning and exploratory data analysis...

## EDA

First we are going to call some typical data analysis libraries.

In [45]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

Save the raw data as a `pandas.DataFrame` object.

In [4]:
raw_data = pd.read_csv('../data/Intelligent_Production_IIoT.csv')

In [6]:
raw_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 45 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   record_id                 15000 non-null  int64
 1   machine_id                15000 non-null  str
 2   production_line           15000 non-null  str
 3   batch_id                  15000 non-null  str
 4   shift                     15000 non-null  str
 5   product_type              15000 non-null  str
 6   ambient_temperature       14611 non-null  float64
 7   humidity                  14599 non-null  float64
 8   air_pressure              14620 non-null  float64
 9   ambient_vibration         15000 non-null  float64
 10  motor_temperature         14639 non-null  float64
 11  spindle_speed             14642 non-null  float64
 12  motor_current             14616 non-null  float64
 13  torque                    14613 non-null  float64
 14  vibration                 14611 non-null  float64
 15  acoustic_level            14628 non-null  float64
 16  bearing_temperature       14630 non-null  float64
 17  process_temperature       14604 non-null  float64
 18  hydraulic_pressure        14628 non-null  float64
 19  flow_rate                 14642 non-null  float64
 20  coolant_temperature       14659 non-null  float64
 21  material_feed_rate        14616 non-null  float64
 22  feed_pressure             14593 non-null  float64
 23  cycle_time                15000 non-null  float64
 24  throughput_rate           15000 non-null  float64
 25  production_volume         15000 non-null  float64
 26  machine_utilization       15000 non-null  float64
 27  resource_utilization      15000 non-null  float64
 28  operator_load             15000 non-null  float64
 29  power_consumption         15000 non-null  float64
 30  energy_per_unit           15000 non-null  float64
 31  defect_rate               15000 non-null  float64
 32  quality_score             15000 non-null  float64
 33  first_pass_yield          15000 non-null  float64
 34  fault_event_count         15000 non-null  int64
 35  downtime_minutes          15000 non-null  float64
 36  maintenance_frequency     15000 non-null  float64
 37  production_cost_per_unit  15000 non-null  float64
 38  resource_efficiency       15000 non-null  float64
 39  production_efficiency     15000 non-null  float64
 40  energy_saving_pct         15000 non-null  float64
 41  downtime_reduction_pct    15000 non-null  float64
 42  cost_reduction_pct        15000 non-null  float64
 43  benefit_score             15000 non-null  float64
 44  operation_mode            15000 non-null  str
dtypes: float64(37), int64(2), str(6)
memory usage: 5.1 MB

In [42]:
raw_data.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
ambient_temperature,14611.0,24.520192,3.217158,15.000000,22.358616,24.548899,26.676740,35.000000
humidity,14599.0,55.002418,10.931021,25.000000,47.580498,55.097578,62.509889,85.000000
air_pressure,14620.0,101.297772,2.072980,96.000000,99.890961,101.319153,102.727663,106.000000
ambient_vibration,15000.0,0.348625,0.119128,0.050000,0.268181,0.349165,0.428356,0.800000
motor_temperature,14639.0,55.181107,5.036548,35.724116,51.784648,55.155338,58.520457,74.289639
spindle_speed,14642.0,2850.524255,423.660252,1500.000000,2559.811083,2851.862022,3135.629252,4000.000000
motor_current,14616.0,24.551220,2.790231,13.720123,22.652374,24.563339,26.471868,35.000000
torque,14613.0,53.090018,5.125547,32.059558,49.620896,53.067941,56.469878,72.608160
vibration,14611.0,1.288602,0.268465,0.238365,1.109383,1.287208,1.470908,2.264449
acoustic_level,14628.0,74.698778,4.397225,59.468260,71.702045,74.675991,77.627434,92.226050
bearing_temperature,14630.0,69.638637,4.490015,51.105215,66.633072,69.620888,72.659319,86.116076
process_temperature,14604.0,79.096056,5.049528,60.441266,75.717918,79.074689,82.454205,98.362417
hydraulic_pressure,14628.0,144.857776,17.889036,90.000000,132.696240,144.833126,157.036433,190.000000
flow_rate,14642.0,67.797916,5.298359,46.264863,64.174242,68.145201,72.096704,75.000000
coolant_temperature,14659.0,22.298056,2.560118,13.252179,20.588518,22.303839,24.003516,33.374523
material_feed_rate,14616.0,77.943481,13.982458,40.000000,68.438256,78.036717,87.587119,115.000000
feed_pressure,14593.0,79.106993,6.674017,50.999859,74.605166,79.126196,83.584622,100.000000
cycle_time,15000.0,32.099246,3.815783,20.000000,29.535842,32.113662,34.650093,47.157408
throughput_rate,15000.0,113.549796,8.075672,83.437338,108.094474,113.550883,119.083805,135.000000
production_volume,15000.0,111.726879,13.428791,74.357002,101.626838,111.205468,121.429494,150.000000
machine_utilization,15000.0,70.135073,5.080929,51.909127,66.655116,70.131180,73.565738,88.802601
resource_utilization,15000.0,85.465002,4.195072,70.388069,82.635608,85.487198,88.337655,99.000000
operator_load,15000.0,62.142525,13.913252,20.000000,52.646818,62.239390,71.619382,95.000000
power_consumption,15000.0,19.784479,1.731123,13.650633,18.609828,19.779331,20.961176,25.000000
energy_per_unit,15000.0,17.695554,1.743578,11.614161,16.284495,17.720944,19.349304,20.000000
defect_rate,15000.0,3.905590,0.744146,0.930878,3.413795,3.905891,4.412720,6.798653
quality_score,15000.0,87.714633,2.192741,78.303258,86.239108,87.675750,89.190007,97.504892
first_pass_yield,15000.0,93.131431,1.499806,87.436516,92.098884,93.121197,94.138597,98.848292
fault_event_count,15000.0,2.124667,1.457097,0.000000,1.000000,2.000000,3.000000,11.000000
downtime_minutes,15000.0,21.206501,6.734687,0.000000,16.577125,20.838395,25.563824,52.418677
maintenance_frequency,15000.0,2.440620,0.652707,0.103708,1.979126,2.404546,2.861697,5.497314
production_cost_per_unit,15000.0,8.122948,0.503077,5.985845,7.781991,8.125447,8.469348,10.331027
resource_efficiency,15000.0,98.964979,0.235137,94.130345,99.000000,99.000000,99.000000,99.000000
production_efficiency,15000.0,98.921282,0.518309,86.848255,99.000000,99.000000,99.000000,99.000000
energy_saving_pct,15000.0,5.524242,3.026324,2.000000,2.689714,5.122888,7.632844,19.370130
downtime_reduction_pct,15000.0,51.171643,8.573631,8.895835,45.568275,51.659942,57.209297,77.733525
cost_reduction_pct,15000.0,28.544505,2.774898,17.854688,26.685312,28.554980,30.386988,39.074997
benefit_score,15000.0,67.214111,1.191964,60.538675,66.454656,67.244797,68.027207,71.490604

In [9]:
raw_data.head(4)

,record_id,machine_id,production_line,batch_id,shift,product_type,ambient_temperature,humidity,air_pressure,ambient_vibration,...,downtime_minutes,maintenance_frequency,production_cost_per_unit,resource_efficiency,production_efficiency,energy_saving_pct,downtime_reduction_pct,cost_reduction_pct,benefit_score,operation_mode
0,1,M07,Line_A,B0343,Morning,Product_C,24.657935,69.272037,102.335679,0.366190,...,25.081059,2.172029,8.028928,99.0,99.0,9.364688,49.353148,26.199425,68.260235,High_Throughput
1,2,M20,Line_E,B0593,Afternoon,Product_D,15.953337,59.927354,100.055317,0.472410,...,20.400191,2.576074,8.537013,99.0,99.0,3.129223,56.434784,30.016525,68.491891,High_Throughput
2,3,M15,Line_E,B0205,Afternoon,Product_C,21.761215,44.487079,102.794636,0.478138,...,11.608597,2.357031,7.372440,99.0,99.0,6.433856,61.539859,33.412663,68.837230,Balanced_Production
3,4,M11,Line_B,B0993,Morning,Product_A,21.973528,59.022870,98.258859,0.417760,...,25.542778,2.840125,8.622625,99.0,99.0,3.284783,43.948708,34.699694,67.074754,Balanced_Production

In [14]:
raw_data['record_id'].describe()

count    15000.000000
mean      7500.500000
std       4330.271354
min          1.000000
25%       3750.750000
50%       7500.500000
75%      11250.250000
max      15000.000000
Name: record_id, dtype: float64

We note that the `production_id` its equal to the indexes, so we can drop it for now on.

In [18]:
raw_data.drop(labels='record_id', axis=1, inplace=True)

Now lets check info about the string-type columns.

In [46]:
data_str_only = raw_data.iloc[:, np.r_[0:5, -1]]
data_str_only

,machine_id,production_line,batch_id,shift,product_type,operation_mode
0,M07,Line_A,B0343,Morning,Product_C,High_Throughput
1,M20,Line_E,B0593,Afternoon,Product_D,High_Throughput
2,M15,Line_E,B0205,Afternoon,Product_C,Balanced_Production
3,M11,Line_B,B0993,Morning,Product_A,Balanced_Production
4,M08,Line_E,B0961,Night,Product_C,Precision_Quality
...,...,...,...,...,...,...
14995,M17,Line_E,B0950,Night,Product_B,Balanced_Production
14996,M18,Line_A,B0252,Afternoon,Product_D,Energy_Efficient
14997,M02,Line_C,B0162,Morning,Product_B,High_Throughput
14998,M03,Line_C,B0927,Night,Product_B,Balanced_Production
14999,M19,Line_D,B0110,Night,Product_A,Precision_Quality

In [31]:
data_str_only['machine_id'].sort_values().value_counts(sort=False)

machine_id
M01    729
M02    738
M03    745
M04    751
M05    735
M06    727
M07    743
M08    743
M09    722
M10    743
M11    684
M12    766
M13    816
M14    713
M15    798
M16    782
M17    812
M18    754
M19    750
M20    749
Name: count, dtype: int64

In [33]:
data_str_only['production_line'].sort_values().value_counts(sort=False)

production_line
Line_A    2982
Line_B    2964
Line_C    2947
Line_D    3024
Line_E    3083
Name: count, dtype: int64

In [37]:
data_str_only['batch_id'].sort_values().value_counts(sort=False)

batch_id
B0001    12
B0002    13
B0003    14
B0004    13
B0005    17
         ..
B0996    18
B0997    15
B0998    13
B0999    14
B1000    22
Name: count, Length: 1000, dtype: int64

In [38]:
data_str_only['shift'].value_counts()

shift
Morning      6039
Afternoon    5681
Night        3280
Name: count, dtype: int64

In [40]:
data_str_only['product_type'].sort_values().value_counts(sort=False)

product_type
Product_A    4464
Product_B    4224
Product_C    3645
Product_D    2667
Name: count, dtype: int64

In [47]:
data_str_only['operation_mode'].sort_values().value_counts(sort=False)

operation_mode
Balanced_Production    5250
Energy_Efficient       3750
High_Throughput        3000
Precision_Quality      3000
Name: count, dtype: int64

In [49]:
raw_data.head(3)

,machine_id,production_line,batch_id,shift,product_type,ambient_temperature,humidity,air_pressure,ambient_vibration,motor_temperature,...,downtime_minutes,maintenance_frequency,production_cost_per_unit,resource_efficiency,production_efficiency,energy_saving_pct,downtime_reduction_pct,cost_reduction_pct,benefit_score,operation_mode
0,M07,Line_A,B0343,Morning,Product_C,24.657935,69.272037,102.335679,0.366190,52.965526,...,25.081059,2.172029,8.028928,99.0,99.0,9.364688,49.353148,26.199425,68.260235,High_Throughput
1,M20,Line_E,B0593,Afternoon,Product_D,15.953337,59.927354,100.055317,0.472410,48.115477,...,20.400191,2.576074,8.537013,99.0,99.0,3.129223,56.434784,30.016525,68.491891,High_Throughput
2,M15,Line_E,B0205,Afternoon,Product_C,21.761215,44.487079,102.794636,0.478138,50.351004,...,11.608597,2.357031,7.372440,99.0,99.0,6.433856,61.539859,33.412663,68.837230,Balanced_Production

In [58]:
machine_data = raw_data.groupby('machine_id')
machine_data